version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=my_cool_secret
      - MARIADB_ROOT_PASSWORD=my-secret-pw
      - MARIADB_DATABASE=wordpress
    # Uncomment this lines if you need comunicate with mariadb 
    #ports:
      #- "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql

  wordpress:
    image: wordpress:6.1-apache
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress-user
      - WORDPRESS_DB_PASSWORD=examplepass
    ports:
      - "8080:80"
    volumes:
      - ./wordpress/:/var/www/html/
